name: Generate Blog Posts

on:
  push:
    paths:
      - 'final/*.ipynb'  # Trigger on notebook changes in notebooks directory
    branches:
      - main

jobs:
  convert-notebook:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for git operations
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert beautifulsoup4 nbformat

    - name: Get changed files
      id: changed-files
      run: |
        echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^final/.*\.ipynb$' | tr '\n' ' ')" >> $GITHUB_OUTPUT

    - name: Convert notebooks to blog posts
      run: |
        # For each changed notebook
        for notebook in ${{ steps.changed-files.outputs.files }}; do
          echo "Processing $notebook"
          python blog_generator.py "$notebook"
        done

    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Check if there are any changes to commit
        if git diff --quiet docs/; then
          echo "No changes to commit"
          exit 0
        fi
        
        git add docs/
        git commit -m "Update blog with new notebook conversions"
        git push
